steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/submission-mgce-asep/api:old", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/submission-mgce-asep/api:old"]
    # Activate Cloud SQL API and Cloud SQL Admin API
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud services enable sqladmin.googleapis.com
        gcloud services enable sql-component.googleapis.com
        gcloud sql instances describe cloud-run-test

  
  # # Run Cloud SQL Proxy
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       ./cloud_sql_proxy -dir=/workspace/cloudsql &
  #       sleep 5
  - name: "gcr.io/cloud-builders/gcloud"
    args: ['beta',
            'run',
            'deploy',
            'api-test',
            '--image',
            'gcr.io/submission-mgce-asep/api:old',
            '--platform',
            'managed',
            '--region',
            'us-central1',
            '--add-cloudsql-instances',
            'submission-mgce-asep:us-central1:cloud-run-test',
            '--allow-unauthenticated',
            '--update-env-vars',
            'DB_HOST = 34.122.1.17',
            'DB_DATABASE = smartrinse_db',
            'DB_NAME = root',
            'DB_PASSWORD = awan123',
            'DB_DIALECT = mysql',
            'ACCESS_TOKEN_SECRET = gugYAF653274t3urg4jrbhjq4rvvrwrvw3523952q34ybadsblaslfhdafas2777jdsfjkehf',
            'REFRESH_TOKEN_SECRET = 874UGugusfjkheatsecfugcehfhshfwiepwjef934095uhfdfnsbfeurutg33r80zsdawu7w'
          ]

